USE mysqldb;
DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FOODS CASCADE;
DROP TABLE IF EXISTS MENU CASCADE;
DROP TABLE IF EXISTS RESTAURANTS CASCADE;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ROLE_ID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID),
    UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS RESTAURANTS
(
    RESTAURANT_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RESTAURANT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MENU
(
    MENU_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME     VARCHAR(255) NOT NULL,
    MENU_DATE     DATETIME     NOT NULL,
    RESTAURANT_ID INT          NOT NULL,
    CONSTRAINT MENU_IBFK_1 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);

CREATE TABLE IF NOT EXISTS FOODS
(
    FOOD_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOOD_NAME VARCHAR(255) NOT NULL,
    PRICE     INT          NOT NULL,
    MENU_ID   INT          NOT NULL,
    CONSTRAINT FOODS_IBFK_1 FOREIGN KEY (MENU_ID) REFERENCES MENU (MENU_ID)
);

CREATE TABLE IF NOT EXISTS VOTING_SYSTEM
(
    VOTING_ID   INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VOTING_DATE DATETIME NOT NULL,
    MENU_ID     INT      NOT NULL,
    USER_ID     INT      NOT NULL,
    CONSTRAINT VOTING_SYSTEM_IBFK_1 FOREIGN KEY (MENU_ID) REFERENCES MENU (MENU_ID),
    CONSTRAINT VOTING_SYSTEM_IBFK_2 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);


INSERT INTO USERS
VALUES (1, 'admin@mail.com', '$2a$11$7wQhfxMtGTZ20pE38nv1f.wbSAKdxb/nT84gXloalHAEKvfv7gqRi');
INSERT INTO ROLES
VALUES (1, 'ROLE_USER');
INSERT INTO ROLES
VALUES (2, 'ROLE_ADMIN');
INSERT INTO USER_ROLES
VALUES (1, 2)



