DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FOODS CASCADE;
DROP TABLE IF EXISTS MENU CASCADE;
DROP TABLE IF EXISTS RESTAURANTS CASCADE;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(22) NOT NULL,
    PASSWORD  VARCHAR(22) NOT NULL
) engine = InnoDB;

CREATE TABLE IF NOT EXISTS ROLES
(
    ROLE_ID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(22) NOT NULL
) engine = InnoDB;;

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID),
    UNIQUE (USER_ID, ROLE_ID)
) engine = InnoDB;;

CREATE TABLE IF NOT EXISTS RESTAURANTS
(
    RESTAURANT_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RESTAURANT_NAME VARCHAR(22) NOT NULL
) engine = InnoDB;;

CREATE TABLE IF NOT EXISTS MENU
(
    MENU_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME    VARCHAR(22) NOT NULL,
    MENU_DATE     DATETIME     NOT NULL,
    RESTAURANT_ID INT          NOT NULL,
    CONSTRAINT MENU_IBFK_1 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
) engine = InnoDB;;

CREATE TABLE IF NOT EXISTS FOODS
(
    FOOD_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOOD_NAME VARCHAR(22) NOT NULL,
    PRICE     INT          NOT NULL,
    MENU_ID   INT          NOT NULL,
    CONSTRAINT FOODS_IBFK_1 FOREIGN KEY (MENU_ID) REFERENCES menu (MENU_ID)
) engine = InnoDB;
